# Default initial positions for manipulator1's ros2_control fake system

initial_positions:
  base_link_j_base_plate: 0
  bevel1_j_bevel_coupler: 0
  bevel_coupler_j_bevel3: 0
  link3_j_bevel1: 0
  motor_holder_j_side_plate_12: 0
  servo_J_gl1: 0
  side_plate1_j_side_plate12: 0