# ~/ws_manipulator4/src/manipulator1_moveit_pkg4/config/moveit_servo.yaml
moveit_servo:
  use_gazebo: false
  status_topic: servo_node/status
  command_out_topic: /Arm_controller/joint_trajectory
  command_out_type: trajectory_msgs/JointTrajectory

  ## Parameters for the Servo loop  
  publish_period: 0.01 
  incoming_command_timeout: 0.1

  ## Stopping and axes
  robot_link_command_frame: base_link 
  ee_frame_name: bevel3 
  planning_group_name: Arm

  ## Collision checking
  check_collisions: true
  collision_check_type: threshold
  self_collision_proximity_threshold: 0.01
  scene_collision_proximity_threshold: 0.02

  ## Smoothing
  smoothing_filter_latency: 0.01