# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Arm_controller
    - Gripper_controller

  Arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12
      - link3_j_bevel1
      - bevel1_j_bevel_coupler
      - bevel_coupler_j_bevel3
      - bevel_coupler_j_bevel2
      
    action_ns: follow_joint_trajectory
    default: true

  Gripper_controller:
    type: FollowJointTrajectory
    joints:
      - servo_J_gl1
      
    action_ns: follow_joint_trajectory
    default: true
