controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    Arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    Gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    servo_controller:
      type: position_controllers/JointGroupPositionController

Arm_controller:
  ros__parameters:
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12
      - link3_j_bevel1
      - bevel1_j_bevel_coupler
      - bevel_coupler_j_bevel3
      - bevel_coupler_j_bevel2

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    allow_partial_joints_goal: true  # <--- MUST BE TRUE

Gripper_controller:
  ros__parameters:
    joints:
      - servo_J_gl1
      - g_main_body_j_gl4M
      - gl2M_j_gl3m

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
  

servo_controller:
  ros__parameters:
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12
      - link3_j_bevel1
      - bevel1_j_bevel_coupler
      - bevel_coupler_j_bevel3
      - bevel_coupler_j_bevel2
