# Specific to your manipulator1 setup
moveit_servo:
  use_gazebo: false # Set to true if using Gazebo
  status_topic: status
  
  # Group properties
  [cite_start]move_group_name: Arm  # 
  [cite_start]planning_frame: base_link # 
  [cite_start]ee_frame_name: bevel3 # 
  robot_link_command_frame: base_link

  # Stopping and Warning Velocity Limits
  # Derived from your pilz_cartesian_limits.yaml where applicable [cite: 22]
  incoming_command_timeout: 0.1
  publish_period: 0.01  # 100Hz
  
  # Collision Checking
  check_collisions: true
  collision_check_type: threshold
  self_collision_proximity_threshold: 0.01
  scene_collision_proximity_threshold: 0.05

  # Smoothing and Limits
  scale:
    linear:  0.4  # Max linear velocity scale
    rotational: 0.8 # Max rotational velocity scale
    joint: 0.5 # Max joint velocity scale

  # Output topic for the controller
  # Your current controller is "Arm_controller" 
  command_out_topic: /Arm_controller/joint_trajectory
  publish_joint_positions: true
  publish_joint_velocities: false
  publish_joint_accelerations: false