controller_joint_names: [
  '',
  'base_link_j_base_plate',
  'side_plate1_j_side_plate12',
  'motor_holder_j_side_plate_12',
  'link3_j_bevel1',
  'bevel_coupler_j_bevel3',
  'servo_J_gl1',
]
