# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  base_link_j_base_plate:
    # --- START OF CHANGE ---
    has_position_limits: true
    min_position: -3.14159  # Allow -180 degrees
    max_position: 3.14159   # Allow +180 degrees
    # --- END OF CHANGE ---
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0

  motor_holder_j_side_plate_12:
    # --- START OF CHANGE ---
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    # --- END OF CHANGE ---
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0.0

  side_plate1_j_side_plate12:
    # --- START OF CHANGE ---
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    # --- END OF CHANGE ---
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0.0