# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Arm_controller

  Arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12