# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    Arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # ADDED: The controller for MoveIt Servo
    servo_velocity_controller:
      type: position_controllers/JointGroupPositionController

Arm_controller:
  ros__parameters:
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# ADDED: Configuration for the Servo Controller
servo_velocity_controller:
  ros__parameters:
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity