# Default initial positions for manipulator1's ros2_control fake system

# initial_positions:
#   base_link_j_base_plate: 0.1
#   bevel_coupler_j_bevel3: 0.0
#   link3_j_bevel1: 0.1
#   motor_holder_j_side_plate_12: 0.1
#   servo_J_gl1: 0.1
#   side_plate1_j_side_plate12: 0.1







initial_positions:
  base_link_j_base_plate: 0.0

  # Shoulder bent forward
  side_plate1_j_side_plate12: 0.0     # ~ -70°

  # Elbow bent downward
  motor_holder_j_side_plate_12:  0.0   # ~ +50°

  # Wrist roll neutral
  link3_j_bevel1: 0.0

  # Wrist pitch slightly down
  bevel_coupler_j_bevel3: 0.0

  # Tool
  servo_J_gl1: 0.0
