# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - manipulator1_body_controller
    - manipulator1_gripper_controller

  manipulator1_body_controller:
    type: FollowJointTrajectory
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12
      - link3_j_bevel1
      - bevel_coupler_j_bevel3
    action_ns: follow_joint_trajectory
  manipulator1_gripper_controller:
    type: GripperCommand
    joints:
      - servo_J_gl1
    action_ns: gripper_cmd
    default: true