# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    manipulator1_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    manipulator1_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator1_body_controller:
  ros__parameters:
    joints:
      - base_link_j_base_plate
      - side_plate1_j_side_plate12
      - motor_holder_j_side_plate_12
      - link3_j_bevel1
      - bevel_coupler_j_bevel3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
manipulator1_gripper_controller:
  ros__parameters:
    joint: servo_J_gl1